### ISSUE TITLE
[FEATURE] Add "description" field to county access rule

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/health-building-block#78]
**[Re: University Monday 2020/10/26 - 2.3]**
> Yes it requires a new field "description".

**Description**
We need new string field "description" for county access rule. It needs to be optional. 
It is needed so that we are able to construct dynamic content of status panel in Safer app.

Json example:
```
{
  "id": "111222",
  "county_id": "333444",
  "description": "this is a description",
  "rules": [
    {
      "county_status_id": "555666",
      "value": "granted"
    },
    {
      "county_status_id": "777888",
      "value": "denied"
    }
  ]
}
```

**Comment by sandeep-ps** [comment]
Closing this issue before archiving the repository. Thanks.
